2024-07-19, Version 22.5.1 (Current)
Notable changes:

This release fixes a regression introduced in Node.js 22.5.0. The
problem is known to display the following symptoms:

- Crash with
```
FATAL ERROR: v8::Object::GetCreationContextChecked No creation context available
```

- npm errors with `npm error Exit handler never called!`

- yarn hangs or outputs
```
Usage Error: Couldn't find the node_modules state file - running an install might help (findPackageLocation)
```

PR-URL: https://github.com/nodejs/node/pull/53935
Refs: https://github.com/nodejs/node/issues/53902
Refs: https://github.com/npm/cli/issues/7657
Refs: https://github.com/yarnpkg/berry/issues/6398