deps: use proper C standard when building libuv
Upstream libuv commits:
https://github.com/libuv/libuv/commit/bb706f5fe71827f667f0bce532e95ce0698a498d
https://github.com/libuv/libuv/commit/018363a163e8901ac2b90100ee436d9472847ffa

libuv was updated to 1.51.0 in 0315283cbdb7745c7e35bb49ac48b0ebcadcb228.
v1.51.0 was the release updating from c90 to c11.
The standard was back then also updated from c89 to c90. and C89 was
never an official standard to begin with. So, I wonder how this managed
to stay without breaking anyone's builds for this long. This atleast
breaks the builds for Android using NDK r28b and r28a, as LLONG_MAX is
not defined by the Clang compiler for older C standards.

Fixes:
../../deps/uv/src/unix/linux.c:2331:36:
error: use of undeclared identifier 'LLONG_MAX'
 2331 |     constraint->quota_per_period = LLONG_MAX;
      |                                    ^
1 error generated.

PR-URL: https://github.com/nodejs/node/pull/58587
Reviewed-By: Luigi Pinca <luigipinca@gmail.com>
Reviewed-By: Anna Henningsen <anna@addaleax.net>
Reviewed-By: Juan José Arboleda <soyjuanarbol@gmail.com>