include missing header malloc.h
building using musl fails due to missing header:
```
../../deps/LIEF/third-party/spdlog/include/spdlog/fmt/bundled/format.h:747:28: error: use of undeclared identifier 'malloc'
  747 |     T* p = static_cast<T*>(malloc(n * sizeof(T)));
      |                            ^~~~~~
../../deps/LIEF/third-party/spdlog/include/spdlog/fmt/bundled/format.h:752:35: error: call to function 'free' that is neither visible in the template definition nor found by argument-dependent lookup
  752 |   void deallocate(T* p, size_t) { free(p); }
      |                                   ^
```

see-also: https://bugs.gentoo.org/977458
fix: #63920
Signed-off-by: Pepper Gray <hello@peppergray.xyz>