test: add crypto check to crypto-lazy-transform
When configuring --without-ssl test-crypto-lazy-transform-writable.js
fails with the following error:

Path: parallel/test-crypto-lazy-transform-writable
internal/util.js:83
    throw new Error('Node.js is not compiled with openssl crypto
support');
    ^

Error: Node.js is not compiled with openssl crypto support
    at Object.exports.assertCrypto (internal/util.js:83:11)
    at crypto.js:28:14
    at NativeModule.compile (bootstrap_node.js:557:7)
    at Function.NativeModule.require (bootstrap_node.js:500:18)
    at Function.Module._load (module.js:446:25)
    at Module.require (module.js:526:17)
    at require (internal/module.js:19:18)
    at Object.<anonymous>
(/Users/danielbevenius/work/nodejs/node/test/parallel/test-crypto-lazy-transform-writable.js:5:16)
    at Module._compile (module.js:607:30)
    at Object.Module._extensions..js (module.js:618:10)
Command: out/Release/node
/Users/danielbevenius/work/nodejs/node/test/parallel/test-crypto-lazy-transform-writable.js
[01:29|% 100|+ 1461|-   1]: Done
make: *** [test] Error 1

This commit add a hasCrypto check like other crypto tests do.