deps: backport e28183b5 from upstream V8
Original commit message:

    Fix compilation with GCC 5.2

    Fixes:

    ../../test/cctest/compiler/test-js-typed-lowering.cc:224:14:
     error: ‘kJSTypes’ defined but not used [-Werror=unused-variable]
      static Type* kJSTypes[] = {Type::Undefined(), Type::Null(),   Type::Boolean(),

    ../../src/bignum.cc: In member function
     ‘void v8::internal::Bignum::AssignDecimalString(Vector<const char>)’:
      ../../src/bignum.cc:80:6: error: assuming signed overflow does not occur when
      assuming that (X + c) < X is always false [-Werror=strict-overflow]

    ../../src/compiler/ia32/code-generator-ia32.cc:1366:3:
      required from here ../../src/base/logging.h:123:26:
       error: comparison between signed and unsigned integer expressions
       [-Werror=sign-compare] DEFINE_CHECK_OP_IMPL(EQ, ==)

    BUG=

    Review URL: https://codereview.chromium.org/1371823002

    Cr-Commit-Position: refs/heads/master@{#31095}