quic: add v8 namespace qualifier to PropertyAttribute
Currently, the are a few compilation errors genereate, similar to the
following:

In file included from ../test/cctest/test_quic_verifyhostnameidentity.cc:4:
../src/quic/node_quic_util-inl.h:329:7: error:
use of undeclared identifier 'PropertyAttribute';
did you mean 'v8::PropertyAttribute'?
      PropertyAttribute::ReadOnly).Check();
      ^~~~~~~~~~~~~~~~~
      v8::PropertyAttribute
../deps/v8/include/v8.h:3433:6: note: 'v8::PropertyAttribute' declared here
enum PropertyAttribute {
     ^

This commit adds the missing namespace qualifier.

PR-URL: https://github.com/nodejs/quic/pull/284
Reviewed-By: James M Snell <jasnell@gmail.com>