src: add missing semicolon
This fixes:

| In file included from ../src/node_crypto.h:47,
|                  from ../src/node.cc:46:
| ../src/crypto/crypto_scrypt.h:80:2: error: expected ';' after struct definition
|    80 | }
|       |  ^
|       |  ;

Signed-off-by: MarkusVolk <f_l_k@t-online.de>