deps: V8: backport 151d0a44a1b2
Original commit message:

    Fix gcc build

    For json-parser.h:

    ```
    ../../src/json/json-parser.h:298:13: error: explicit specialization in
    non-namespace scope 'class v8::internal::JsonParser<Char>'
      298 |   template <>
          |             ^
    ../../src/json/json-parser.h:299:18: error: template-id
    'IsNextToken<v8::internal::JsonToken::EOS>' in declaration of primary template
      299 |   V8_INLINE bool IsNextToken<JsonToken::EOS>() {
          |                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~
    ```

    For wasm-objects.cc:
    ```
    ../../src/wasm/wasm-objects.cc:2522:45: error: no matching function for call to
    'v8::internal::WasmDispatchTable::SetForNonWrapper<v8::internal::WasmDispatchTable>(
     v8::internal::WasmDispatchTable&, int&, v8::internal::Tagged<v8::internal::
     Union<v8::internal::Smi, v8::internal::WasmTrustedInstanceData> >&,
     v8::internal::WasmCodePointer&, v8::internal::wasm::CanonicalTypeIndex&,
     v8::internal::WasmDispatchTable::NewOrExistingEntry&)'
    ```

    ```
    error: no matching function for call to 'v8::internal::WasmDispatchTable::
    SetForWrapper<v8::internal::WasmDispatchTable>(v8::internal::WasmDispatchTable&,
    int&, v8::internal::Tagged<v8::internal::WasmImportData>&, std::shared_ptr<v8::
    internal::wasm::WasmImportWrapperHandle>&, v8::internal::wasm::
    CanonicalTypeIndex&, v8::internal::WasmDispatchTable::NewOrExistingEntry&)'
    ```

    For the fix fully qualify calls to SetForWrapper and SetForNonWrapper with
    ::v8::internal:: to avoid accidental lookup of class member names.
    This resolves template resolution errors caused by unqualified
    calls inside WasmDispatchTable and WasmDispatchTableForImports
    member functions.

    Change-Id: I687935a05dc754db686deaa0f93079d350aae07e
    Reviewed-on: https://chromium-review.googlesource.com/c/v8/v8/+/7107891
    Reviewed-by: Patrick Thier <pthier@chromium.org>
    Reviewed-by: Manos Koukoutos <manoskouk@chromium.org>
    Commit-Queue: Milad Farazmand <mfarazma@ibm.com>
    Cr-Commit-Position: refs/heads/main@{#103547}

Refs: https://github.com/v8/v8/commit/151d0a44a1b2fa5dcdc1282101f71916f303aae6
Co-authored-by: Michaël Zasso <targos@protonmail.com>