repl: Add tests for repl eval of `let process;`
These changes are meant to address concerns aired in
https://github.com/nodejs/node/issues/6802. A test case has been added
which tests the behavior of `let process;` when `useGlobal` is `false`
or `undefined`. As mentioned in the test comments, setting `useGlobal`
to `true` generates the the expected exception, and the `catch` block
executes in the test code as expected. But the test framework detects
this exception being thrown and fails the build.

    /usr/bin/python tools/test.py --mode=release -J \
        addon doctool known_issues message parallel sequential
        === release test-repl-use-global ===
        Path: parallel/test-repl-use-global
        domain.js:99
                process._emittingTopLevelDomainError = false;
                                                             ^

    TypeError: Cannot set property '_emittingTopLevelDomainError' of
     undefined
        at Domain.errorHandler [as _errorHandler] (domain.js:99:46)
            at process._fatalException (node.js:269:33)
            Command: out/Release/node --expose-internals
            /Users/lanceball/src/node/test/parallel/test-repl-use-global.js
            [00:52|% 100|+ 1113|-   1]: Done
            make: *** [test] Error 1