test: disable cctests that fail when built with NODE_BUILTIN_MODULES_PATH
A number of tests that call ToLocalChecked() on the return value of
LoadEnvironment() in test/cctest and test/embedding fails with:
FATAL ERROR: v8::ToLocalChecked Empty MaybeLocal.
when run against a binary built with NODE_BUILTIN_MODULES_PATH.
This change disables those tests, so that make cctest passes.

Signed-off-by: Darshan Sen <darshan.sen@postman.com>