build: add check for empty openssl-fips flag
Currently, when specifying the --openssl-fips flag without any path
, or an empty path, does not generate an error. If a path is specified
then the following error is generated:

ERROR: FIPS is not supported in this version of Node.js

This commit adds a check so that the error is generated even if the
path is empty.