repl: REPL enhancements
* Welcome message with version and help guide
    * `displayWelcomeMessage` flag is used to
      turn on/off
* Differentiate execute & continue actions
    * ^M or enter key to execute the command
    * ^J to continue building multiline expression.
    * `executeOnTimeout` value is used to determine
      the end of expression when `terminal` is false.
* Pretty stack trace.
    * REPL specific stack frames are removed before
      emitting to output stream.
* Recoverable errors.
    * No more recoverable errors & no false positives.
* Defined commands(like .exit, .load) are meaningful
  only at the top level.
* Remove `.break` command.

Welcome message template
------------------------
```js
$ node
Welcome to Node.js <<version>> (<<vm name>> VM, <<vm version>>)
Type ^M or enter to execute, ^J to continue, ^C to exit
Or try

```

Pretty stack trace
------------------
```js
$ node -i
> throw new Error('tiny stack')
Error: tiny stack
    at repl:1:7
> var x y;
var x y;
      ^
SyntaxError: Unexpected identifier
>
```