src: suppress compilation warning in inspector_socket.cc
When building/linking against OpenSSL 3.0.0alpha17 the following
compilation error occurs:

In file included from ../src/inspector_socket.cc:7:
../src/inspector_socket.cc: In function
‘void node::inspector::{anonymous}::generate_accept_string(
    const string&, char (*)[28])’:
../src/inspector_socket.cc:150:8: error:
second operand of conditional expression has no effect
[-Werror=unused-value]
  150 |  reinterpret_cast<unsigned char*>(hash));
      |  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../deps/openssl/openssl/include/openssl/sha.h:57:57: note:
in definition of macro ‘SHA1’
   57 |  (EVP_Q_digest(NULL, "SHA1", NULL, d, n, md, NULL) ? md : NULL)
      |                                                      ^~
../src/inspector_socket.cc:150:47: error:
third operand of conditional expression has no effect
[-Werror=unused-value]
  150 |        reinterpret_cast<unsigned char*>(hash));
      |                                               ^

This commit suppresses this warning for OpenSSL 3.0.